version: "3.8"

services:
  express:
    build: ./backend/express
    ports:
      - "3000:3000"
    environment:
      - PYTHON_API_URL=http://python:8000
    depends_on:
      - python
      - akavelink

  python:
    build: ./backend/python
    ports:
      - "8000:8000"
    environment:
      - NODE_ADDRESS=connect.akave.ai:5500
      - WEB3_PRIVATE_KEY=${PRIVATE_KEY}
      - AUTH_PRIVATE_KEY=${PRIVATE_KEY}
    volumes:
      - ~/.key:/keys
    depends_on:
      - akavelink

  akavelink:
    image: akave/akavelink:latest
    ports:
      - "8080:3000"
    environment:
      - NODE_ADDRESS=connect.akave.ai:5500
      - PRIVATE_KEY=${HEX_PRIVATE_KEY}

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000  # Express server URL
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - express
      - python
